site:
  url: 'http://localhost/addon-highlight/demo/'

theme:
  activate:
    - core/basic
  css:
    bundle: false
    minify: false
  js:
    bundle: false
    minify: false

addons:
  activate:
    - syntax-highlighting

templates:
  site:
    name: Demo Leafcutter site

cache:
  driver: ephemeral
  directory: '${base_dir}/cache/'

assets:
  output:
    directory: '${base_dir}/assets/'
    url: '@/assets/'
